{"uuid": "1fb12aac-bf33-416b-a3a8-22ab879c3670", "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service drivers/chromedriver unexpectedly exited. Status code was: -9\n\n", "trace": "  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/_pytest/fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/PycharmProjects/pythonProject/Automation/steps/conftest.py\", line 30, in init_driver\n    driver = webdriver.Chrome(service=service,options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 50, in __init__\n    self.service.start()\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/selenium/webdriver/common/service.py\", line 102, in start\n    self.assert_process_still_running()\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/selenium/webdriver/common/service.py\", line 115, in assert_process_still_running\n    raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\n"}, "start": 1711774194891, "stop": 1711774209949}], "start": 1711774194891, "stop": 1711774210037}