{"uuid": "0b334643-d4c1-468e-a4b2-54e7108807b1", "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'config/envInfo.yml'\n", "trace": "  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/_pytest/fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/PycharmProjects/pythonProject/Automation/steps/conftest.py\", line 20, in init_driver\n    with open('config/envInfo.yml', 'r') as f:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1712118978582, "stop": 1712118978582}], "start": 1712118978582, "stop": 1712118978640}