{"uuid": "9c311550-689a-4147-9485-dfa86c9bbb6e", "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "ValueError: Timeout value connect was <object object at 0x100cd4910>, but it must be an int, float or None.\n", "trace": "  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/_pytest/fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/PycharmProjects/pythonProject/Automation/steps/conftest.py\", line 27, in init_driver\n    driver = webdriver.Chrome(options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 76, in __init__\n    RemoteWebDriver.__init__(\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py\", line 397, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/urllib3/_request_methods.py\", line 144, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/urllib3/_request_methods.py\", line 279, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/urllib3/poolmanager.py\", line 433, in urlopen\n    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/urllib3/poolmanager.py\", line 304, in connection_from_host\n    return self.connection_from_context(request_context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/urllib3/poolmanager.py\", line 329, in connection_from_context\n    return self.connection_from_pool_key(pool_key, request_context=request_context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/urllib3/poolmanager.py\", line 352, in connection_from_pool_key\n    pool = self._new_pool(scheme, host, port, request_context=request_context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/urllib3/poolmanager.py\", line 266, in _new_pool\n    return pool_cls(host, port, **request_context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 196, in __init__\n    timeout = Timeout.from_float(timeout)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/urllib3/util/timeout.py\", line 186, in from_float\n    return Timeout(read=timeout, connect=timeout)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/urllib3/util/timeout.py\", line 115, in __init__\n    self._connect = self._validate_timeout(connect, \"connect\")\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/urllib3/util/timeout.py\", line 152, in _validate_timeout\n    raise ValueError(\n"}, "start": 1710821589768, "stop": 1710821590792}], "start": 1710821589768, "stop": 1710821590900}