{"uuid": "9986eef7-1a05-49fc-9b5e-8fe0b23f1122", "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 117\nCurrent browser version is 122.0.6261.94 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome\n\n", "trace": "  File \"/Users/saravanakumar/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 900, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/PycharmProjects/pythonProject/steps/conftest.py\", line 15, in init_driver\n    driver = webdriver.Chrome('drivers/chromedriver')\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 76, in __init__\n    RemoteWebDriver.__init__(\n  File \"/Users/saravanakumar/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/saravanakumar/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/saravanakumar/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1709487711918, "stop": 1709487720094}], "start": 1709487711918, "stop": 1709487720187}