{"name": "test_sample01[123-123--]", "status": "broken", "statusDetails": {"message": "ValueError: Timeout value connect was <object object at 0x102108900>, but it must be an int, float or None.", "trace": ".0 = <list_iterator object at 0x104111120>\n\n>   kwargs = {arg: kwargs[arg] if arg in kwargs else request.getfixturevalue(arg) for arg in args}\n\n../../../Automation/lib/python3.11/site-packages/pytest_bdd/scenario.py:204: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n../../../Automation/lib/python3.11/site-packages/_pytest/fixtures.py:541: in getfixturevalue\n    fixturedef = self._get_active_fixturedef(argname)\n../../../Automation/lib/python3.11/site-packages/_pytest/fixtures.py:570: in _get_active_fixturedef\n    self._compute_fixture_value(fixturedef)\n../../../Automation/lib/python3.11/site-packages/_pytest/fixtures.py:647: in _compute_fixture_value\n    fixturedef.execute(request=subrequest)\n../../../Automation/lib/python3.11/site-packages/_pytest/fixtures.py:1079: in execute\n    result = ihook.pytest_fixture_setup(fixturedef=self, request=request)\n../../../Automation/lib/python3.11/site-packages/pluggy/_hooks.py:501: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n../../../Automation/lib/python3.11/site-packages/pluggy/_manager.py:119: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n../../../Automation/lib/python3.11/site-packages/_pytest/setuponly.py:36: in pytest_fixture_setup\n    return (yield)\n../../../Automation/lib/python3.11/site-packages/_pytest/fixtures.py:1132: in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n../../../Automation/lib/python3.11/site-packages/_pytest/fixtures.py:906: in call_fixture_func\n    fixture_result = next(generator)\nsteps/conftest.py:15: in init_driver\n    driver = webdriver.Chrome('drivers/chromedriver')\n../../../Automation/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py:76: in __init__\n    RemoteWebDriver.__init__(\n../../../Automation/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:157: in __init__\n    self.start_session(capabilities, browser_profile)\n../../../Automation/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:252: in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n../../../Automation/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:319: in execute\n    response = self.command_executor.execute(driver_command, params)\n../../../Automation/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py:374: in execute\n    return self._request(command_info[0], url, body=data)\n../../../Automation/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py:397: in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n../../../Automation/lib/python3.11/site-packages/urllib3/_request_methods.py:144: in request\n    return self.request_encode_body(\n../../../Automation/lib/python3.11/site-packages/urllib3/_request_methods.py:279: in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n../../../Automation/lib/python3.11/site-packages/urllib3/poolmanager.py:433: in urlopen\n    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)\n../../../Automation/lib/python3.11/site-packages/urllib3/poolmanager.py:304: in connection_from_host\n    return self.connection_from_context(request_context)\n../../../Automation/lib/python3.11/site-packages/urllib3/poolmanager.py:329: in connection_from_context\n    return self.connection_from_pool_key(pool_key, request_context=request_context)\n../../../Automation/lib/python3.11/site-packages/urllib3/poolmanager.py:352: in connection_from_pool_key\n    pool = self._new_pool(scheme, host, port, request_context=request_context)\n../../../Automation/lib/python3.11/site-packages/urllib3/poolmanager.py:266: in _new_pool\n    return pool_cls(host, port, **request_context)\n../../../Automation/lib/python3.11/site-packages/urllib3/connectionpool.py:196: in __init__\n    timeout = Timeout.from_float(timeout)\n../../../Automation/lib/python3.11/site-packages/urllib3/util/timeout.py:186: in from_float\n    return Timeout(read=timeout, connect=timeout)\n../../../Automation/lib/python3.11/site-packages/urllib3/util/timeout.py:115: in __init__\n    self._connect = self._validate_timeout(connect, \"connect\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'urllib3.util.timeout.Timeout'>, value = <object object at 0x102108900>, name = 'connect'\n\n    @classmethod\n    def _validate_timeout(cls, value: _TYPE_TIMEOUT, name: str) -> _TYPE_TIMEOUT:\n        \"\"\"Check that a timeout attribute is valid.\n    \n        :param value: The timeout value to validate\n        :param name: The name of the timeout attribute to validate. This is\n            used to specify in error messages.\n        :return: The validated and casted version of the given value.\n        :raises ValueError: If it is a numeric value less than or equal to\n            zero, or the type is not an integer, float, or None.\n        \"\"\"\n        if value is None or value is _DEFAULT_TIMEOUT:\n            return value\n    \n        if isinstance(value, bool):\n            raise ValueError(\n                \"Timeout cannot be a boolean value. It must \"\n                \"be an int, float or None.\"\n            )\n        try:\n            float(value)\n        except (TypeError, ValueError):\n>           raise ValueError(\n                \"Timeout value %s was %s, but it must be an \"\n                \"int, float or None.\" % (name, value)\n            ) from None\nE           ValueError: Timeout value connect was <object object at 0x102108900>, but it must be an int, float or None.\n\n../../../Automation/lib/python3.11/site-packages/urllib3/util/timeout.py:152: ValueError"}, "description": "../features/sample.feature: Verify the login functionality", "parameters": [{"name": "_pytest_bdd_example", "value": "{'Username': '123', 'Password': '123'}"}, {"name": "Username", "value": "''"}, {"name": "Password", "value": "''"}], "start": 1710782714795, "stop": 1710782715832, "uuid": "032b4ac6-2156-4d76-b8c4-afad8a490c2d", "historyId": "aa800b01451927b0f97456ee7ee977c5", "testCaseId": "8781a52a01f4bb11b862418b60a465e1", "fullName": "steps.test_sample#test_sample01", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('Username', 'Password')"}, {"name": "tag", "value": "sample01"}, {"name": "parentSuite", "value": "steps"}, {"name": "suite", "value": "test_sample"}, {"name": "host", "value": "Saravanas-MacBook-Air.local"}, {"name": "thread", "value": "1933-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "steps.test_sample"}]}